name: Build and push Docker image to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tags
        run: |
          DATETIME_TAG=$(git log -1 --format=%cd --date=format:'%Y%m%d%H%M%S')
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "DATETIME_TAG=$DATETIME_TAG" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build \
            -t ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:${{ env.DATETIME_TAG }} \
            -t ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:${{ env.COMMIT_SHA }} \
            -t ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:latest .
          
          docker push ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:${{ env.DATETIME_TAG }}
          docker push ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:${{ env.COMMIT_SHA }}
          docker push ${{ secrets.ECR_REPOSITORY_URI_SAMPLE }}:latest